// Generated by generate_kama_mavp.py using Python Decimal arithmetic (50 digits).
// The formulas are independent, direct definitions of KAMA and EMA-selected MAVP.

pub const REFERENCE_METHOD: &str = "Python Decimal, precision=50, direct definition";
pub const TALIB_GIT_REVISION: &str = "e64d2ac896c595f38d65e44c812efbfdac8a64cf";
pub const TALIB_KAMA_SOURCE: &str = "src/ta_func/ta_KAMA.c";
pub const TALIB_MAVP_SOURCE: &str = "src/ta_func/ta_MAVP.c";
pub const KAMA_PERIOD: usize = 5;
pub const MAVP_MINIMUM_PERIOD: usize = 2;
pub const MAVP_MAXIMUM_PERIOD: usize = 5;

pub const INPUT: &[f64] = &[
    10.0, 10.5, 10.25, 11.0, 10.75, 12.0, 11.5, 13.0, 12.75, 14.0, 13.0, 15.0, 14.5, 16.0, 15.25,
    17.0, 16.5, 18.0, 17.25, 19.0,
];

pub const PERIOD_SELECTIONS: &[usize] =
    &[1, 2, 3, 4, 5, 0, 2, 9, 4, 3, 5, 2, 4, 8, 1, 3, 5, 4, 2, 0];

pub const KAMA_EXPECTED: &[f64] = &[
    11.021386544366079,
    11.055056297877100,
    11.456192800284205,
    11.610652513734326,
    12.153190808957111,
    12.186498982839169,
    12.672855397670890,
    12.782674203321806,
    13.241489785136393,
    13.318191493886845,
    14.015106929086018,
    14.164459087021493,
    14.827490632415808,
    14.932182523739830,
    15.669723124222214,
];

pub const MAVP_EMA_EXPECTED: &[f64] = &[
    10.500000000000000,
    11.625000000000000,
    11.541666666666666,
    11.777777777777779,
    12.289800000000000,
    13.239583333333334,
    12.823045267489713,
    14.395233196159122,
    14.074358080000000,
    14.577198597774730,
    15.329453081339226,
    16.097493489583332,
    15.856206991933254,
    16.849462084300800,
    17.331227815819002,
    18.443742605273002,
];
