#!/usr/bin/env python3
"""Regenerate deterministic SAR/SAREXT Rust fixtures through TA-Lib 0.6.4."""

from __future__ import annotations

import argparse
from pathlib import Path
from typing import Iterable

import numpy as np
import talib

TALIB_VERSION = "0.6.4"
TALIB_GIT_REVISION = "43f9d5042ecc4bd367941846494ad907bf20ea50"
TALIB_SOURCE_ARCHIVE_SHA256 = (
    "aa04066d17d69c73b1baaef0883414d3d56ab3775872d82916d1cdb376a3ae86"
)
HIGH = np.array([
    51.12, 52.35, 52.1, 51.8, 52.1, 52.5, 52.8, 52.5, 53.5, 53.5, 53.8, 54.2,
    53.4, 53.5, 54.4, 55.2, 55.7, 57, 57.5, 58, 57.7, 58, 57.5, 57, 56.7, 57.5,
    56.7, 56, 56.2, 54.8, 55.5, 54.7, 54, 52.5, 51, 51.5, 51.7, 53,
], dtype=np.float64)
LOW = np.array([
    50, 51.5, 51, 50.5, 51.25, 51.7, 51.85, 51.5, 52.3, 52.5, 53, 53.5, 52.5,
    52.1, 53, 54, 55, 56, 56.5, 57, 56.5, 57.3, 56.7, 56.3, 56.2, 56, 55.5, 55,
    54.9, 54, 54.5, 53.8, 53, 51.5, 50, 50.5, 50.2, 51.5,
], dtype=np.float64)
EXT = (-53.0, 0.01, 0.03, 0.015, 0.18, 0.04, 0.025, 0.22)


def rust_slice(values: Iterable[float]) -> str:
    return "\n".join(f"    {float(value)!r}," for value in values)


def render() -> str:
    sar = talib.SAR(HIGH, LOW, acceleration=0.02, maximum=0.2)
    sarext = talib.SAREXT(
        HIGH,
        LOW,
        startvalue=EXT[0],
        offsetonreverse=EXT[1],
        accelerationinitlong=EXT[2],
        accelerationlong=EXT[3],
        accelerationmaxlong=EXT[4],
        accelerationinitshort=EXT[5],
        accelerationshort=EXT[6],
        accelerationmaxshort=EXT[7],
    )
    return f'''// Generated by tests/fixtures/generate_sar_reference.py. Do not edit by hand.
// Reference source: TA-Lib v{TALIB_VERSION}, commit {TALIB_GIT_REVISION}.
// Source archive SHA-256: {TALIB_SOURCE_ARCHIVE_SHA256}.

pub const TALIB_VERSION: &str = "{TALIB_VERSION}";
pub const TALIB_GIT_REVISION: &str = "{TALIB_GIT_REVISION}";
pub const TALIB_SOURCE_ARCHIVE_SHA256: &str =
    "{TALIB_SOURCE_ARCHIVE_SHA256}";
pub const OUTPUT_BEGIN: usize = 1;

pub const HIGH: &[f64] = &[
{rust_slice(HIGH)}
];
pub const LOW: &[f64] = &[
{rust_slice(LOW)}
];
pub const SAR_DEFAULT: &[f64] = &[
{rust_slice(sar[1:])}
];
pub const SAREXT_PARAMETERS: [f64; 8] = {list(EXT)!r};
pub const SAREXT_CUSTOM: &[f64] = &[
{rust_slice(sarext[1:])}
];
'''


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--output",
        type=Path,
        default=Path(__file__).with_name("sar_reference.rs"),
    )
    args = parser.parse_args()
    reported = talib.__ta_version__
    if isinstance(reported, bytes):
        reported = reported.decode("ascii")
    if not str(reported).startswith(TALIB_VERSION):
        raise RuntimeError(f"expected TA-Lib {TALIB_VERSION}, got {reported}")
    args.output.write_text(render())


if __name__ == "__main__":
    main()
