#!/usr/bin/env python3
"""Regenerate the auditable RSI/CMO/IMI decimal reference fixture.

The formulas follow TA-Lib 0.8.1 at commit
`e64d2ac896c595f38d65e44c812efbfdac8a64cf`: `ta_RSI.c`, `ta_CMO.c`,
and `ta_IMI.c`. Decimal arithmetic makes the generator independent of the Rust
implementation while preserving each definition's operation and source shape.
"""

from __future__ import annotations

import argparse
from decimal import Decimal, getcontext
from pathlib import Path

getcontext().prec = 50
PERIOD = 5
TALIB_VERSION = "0.8.1"
TALIB_GIT_REVISION = "e64d2ac896c595f38d65e44c812efbfdac8a64cf"
REAL_TEXT = (
    "44", "44.34", "44.09", "44.15", "43.61", "44.33", "44.83",
    "45.10", "45.42", "45.84", "46.08", "45.89",
)
OPEN_TEXT = ("10", "11", "10", "12", "12", "13", "12", "14", "13", "15")
CLOSE_TEXT = ("11", "10", "10", "13", "11", "14", "13", "13", "15", "15")
REAL = tuple(Decimal(value) for value in REAL_TEXT)
OPEN = tuple(Decimal(value) for value in OPEN_TEXT)
CLOSE = tuple(Decimal(value) for value in CLOSE_TEXT)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--output",
        type=Path,
        default=Path(__file__).with_name("relative_strength_reference.rs"),
        help="Rust fixture file to create",
    )
    return parser.parse_args()


def split(movement: Decimal) -> tuple[Decimal, Decimal]:
    return (movement, Decimal(0)) if movement >= 0 else (Decimal(0), -movement)


def wilder() -> tuple[list[Decimal], list[Decimal]]:
    movements = [split(current - previous) for previous, current in zip(REAL, REAL[1:])]
    gain = sum(pair[0] for pair in movements[:PERIOD]) / PERIOD
    loss = sum(pair[1] for pair in movements[:PERIOD]) / PERIOD
    rsi: list[Decimal] = []
    cmo: list[Decimal] = []
    for index in range(PERIOD, len(movements) + 1):
        denominator = gain + loss
        rsi.append(Decimal(0) if denominator == 0 else Decimal(100) * gain / denominator)
        cmo.append(Decimal(0) if denominator == 0 else Decimal(100) * (gain - loss) / denominator)
        if index < len(movements):
            incoming_gain, incoming_loss = movements[index]
            gain = (gain * (PERIOD - 1) + incoming_gain) / PERIOD
            loss = (loss * (PERIOD - 1) + incoming_loss) / PERIOD
    return rsi, cmo


def imi() -> list[Decimal]:
    movements = [split(close - open_) for open_, close in zip(OPEN, CLOSE)]
    values: list[Decimal] = []
    for end in range(PERIOD - 1, len(movements)):
        window = movements[end - PERIOD + 1:end + 1]
        gain = sum(pair[0] for pair in window)
        loss = sum(pair[1] for pair in window)
        values.append(Decimal(50) if gain + loss == 0 else Decimal(100) * gain / (gain + loss))
    return values


def rust_decimal(value: Decimal) -> str:
    rendered = format(value, ".17g")
    return rendered if "." in rendered or "e" in rendered.lower() else f"{rendered}.0"



def rust_expected(values: list[Decimal]) -> str:
    return "\n".join(f"    {rust_decimal(value)}," for value in values)


def render_fixture() -> str:
    rsi, cmo = wilder()
    imi_values = imi()
    real_values = ", ".join(f"{value}.0" if "." not in value else value for value in REAL_TEXT)
    open_values = ", ".join(f"{value}.0" if "." not in value else value for value in OPEN_TEXT)
    close_values = ", ".join(f"{value}.0" if "." not in value else value for value in CLOSE_TEXT)
    imi_rendered = ", ".join(rust_decimal(value) for value in imi_values)
    return f'''// Generated by tests/fixtures/generate_relative_strength.py. Do not edit by hand.
// Reference source: TA-Lib {TALIB_VERSION}, commit {TALIB_GIT_REVISION}.
// Definitions: src/ta_func/ta_RSI.c, ta_CMO.c, and ta_IMI.c at that revision.

pub const PERIOD: usize = {PERIOD};
pub const TALIB_VERSION: &str = "{TALIB_VERSION}";
pub const TALIB_GIT_REVISION: &str = "{TALIB_GIT_REVISION}";

pub const REAL: &[f64] = &[
    {real_values},
];
pub const RSI_EXPECTED: &[f64] = &[
{rust_expected(rsi)}
];
pub const CMO_EXPECTED: &[f64] = &[
{rust_expected(cmo)}
];

pub const OPEN: &[f64] = &[{open_values}];
pub const CLOSE: &[f64] = &[{close_values}];
pub const IMI_EXPECTED: &[f64] = &[{imi_rendered}];
'''


def main() -> None:
    args = parse_args()
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(render_fixture(), encoding="utf-8")


if __name__ == "__main__":
    main()
