#!/usr/bin/env python3
"""Generate composite Momentum fixtures through pinned TA-Lib ctypes calls."""

from __future__ import annotations

import argparse
import ctypes
import hashlib
import os
from pathlib import Path
import subprocess
import tarfile
import tempfile
from typing import Sequence

TALIB_GIT_REVISION = "43f9d5042ecc4bd367941846494ad907bf20ea50"
TALIB_VERSION = "0.6.4"
TALIB_SOURCE_ARCHIVE_SHA256 = (
    "aa04066d17d69c73b1baaef0883414d3d56ab3775872d82916d1cdb376a3ae86"
)
OPEN = [10.0, 10.8, 11.5, 11.2, 12.0, 12.7, 12.2, 11.6, 11.0, 10.5, 11.1, 11.8]
HIGH = [11.2, 12.0, 12.1, 12.4, 13.1, 13.0, 12.8, 12.0, 11.5, 11.4, 12.0, 12.7]
LOW = [9.6, 10.4, 10.9, 10.8, 11.7, 12.0, 11.8, 10.9, 10.2, 10.0, 10.7, 11.3]
CLOSE = [10.9, 11.7, 11.2, 12.1, 12.8, 12.2, 11.9, 11.1, 10.6, 11.2, 11.7, 12.5]
VOLUME = [100.0, 130.0, 90.0, 160.0, 140.0, 110.0, 150.0, 170.0, 120.0, 180.0, 145.0, 155.0]
CCI_PERIOD = 5
MFI_PERIOD = 5
ULTOSC_PERIODS = (3, 5, 7)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source-archive", required=True, type=Path)
    parser.add_argument("--output", required=True, type=Path)
    return parser.parse_args()


def build_pinned_talib(source_archive: Path, workspace: Path) -> Path:
    digest = hashlib.sha256(source_archive.read_bytes()).hexdigest()
    if digest != TALIB_SOURCE_ARCHIVE_SHA256:
        raise RuntimeError(
            f"TA-Lib archive checksum mismatch: expected {TALIB_SOURCE_ARCHIVE_SHA256}, got {digest}"
        )
    with tarfile.open(source_archive, "r:gz") as archive:
        archive.extractall(workspace)
    source = workspace / f"ta-lib-{TALIB_VERSION}"
    install = workspace / "install"
    subprocess.run(["./configure", f"--prefix={install}"], cwd=source, check=True)
    subprocess.run(["make", f"-j{max(1, os.cpu_count() or 1)}"], cwd=source, check=True)
    subprocess.run(["make", "install"], cwd=source, check=True)
    for name in ("libta-lib.dylib", "libta-lib.so"):
        library = install / "lib" / name
        if library.exists():
            return library
    raise RuntimeError("pinned TA-Lib build did not produce a shared library")


class TalibReference:
    def __init__(self, library_path: Path) -> None:
        self.library = ctypes.CDLL(str(library_path.resolve()))
        self.library.TA_Initialize.restype = ctypes.c_int
        self.library.TA_Shutdown.restype = ctypes.c_int
        self.library.TA_GetVersionString.restype = ctypes.c_char_p
        self._check(self.library.TA_Initialize(), "TA_Initialize")
        reported = self.library.TA_GetVersionString().decode("ascii").split()[0]
        if reported != TALIB_VERSION:
            raise RuntimeError(f"expected TA-Lib {TALIB_VERSION}, got {reported}")

    @staticmethod
    def _check(code: int, operation: str) -> None:
        if code != 0:
            raise RuntimeError(f"{operation} failed with TA-Lib code {code}")

    @staticmethod
    def _array(values: Sequence[float]):
        return (ctypes.c_double * len(values))(*values)

    def _output(self, function, columns: Sequence[Sequence[float]], parameters: Sequence[int]):
        length = len(columns[0])
        arrays = [self._array(column) for column in columns]
        output = (ctypes.c_double * length)()
        begin = ctypes.c_int()
        count = ctypes.c_int()
        arguments = [0, length - 1, *arrays, *parameters, ctypes.byref(begin), ctypes.byref(count), output]
        self._check(function(*arguments), function.__name__)
        return begin.value, list(output[: count.value])

    def bop(self):
        return self._output(self.library.TA_BOP, [OPEN, HIGH, LOW, CLOSE], [])

    def cci(self):
        return self._output(self.library.TA_CCI, [HIGH, LOW, CLOSE], [CCI_PERIOD])

    def mfi(self):
        return self._output(self.library.TA_MFI, [HIGH, LOW, CLOSE, VOLUME], [MFI_PERIOD])

    def ultosc(self):
        return self._output(self.library.TA_ULTOSC, [HIGH, LOW, CLOSE], ULTOSC_PERIODS)

    def close(self) -> None:
        self._check(self.library.TA_Shutdown(), "TA_Shutdown")


def rust_slice(name: str, values: Sequence[float]) -> str:
    body = "\n".join(f"    {value!r}," for value in values)
    return f"pub const {name}: &[f64] = &[\n{body}\n];\n"


def emit(reference: TalibReference, output_path: Path) -> None:
    bop_begin, bop = reference.bop()
    cci_begin, cci = reference.cci()
    mfi_begin, mfi = reference.mfi()
    ultosc_begin, ultosc = reference.ultosc()
    expected_begins = (0, CCI_PERIOD - 1, MFI_PERIOD, max(ULTOSC_PERIODS))
    actual_begins = (bop_begin, cci_begin, mfi_begin, ultosc_begin)
    if actual_begins != expected_begins:
        raise RuntimeError(f"unexpected lookbacks: {actual_begins}")

    text = (
        "// Generated by tests/fixtures/generate_momentum_composite.py. Do not edit by hand.\n"
        f"// Reference source: TA-Lib v{TALIB_VERSION}, commit {TALIB_GIT_REVISION}.\n"
        f"// Source archive SHA-256: {TALIB_SOURCE_ARCHIVE_SHA256}.\n\n"
        f'pub const TALIB_VERSION: &str = "{TALIB_VERSION}";\n'
        f'pub const TALIB_GIT_REVISION: &str = "{TALIB_GIT_REVISION}";\n'
        "pub const TALIB_SOURCE_ARCHIVE_SHA256: &str =\n"
        f'    "{TALIB_SOURCE_ARCHIVE_SHA256}";\n\n'
        + rust_slice("OPEN", OPEN)
        + rust_slice("HIGH", HIGH)
        + rust_slice("LOW", LOW)
        + rust_slice("CLOSE", CLOSE)
        + rust_slice("VOLUME", VOLUME)
        + f"\npub const CCI_PERIOD: usize = {CCI_PERIOD};\n"
        + f"pub const MFI_PERIOD: usize = {MFI_PERIOD};\n"
        + f"pub const ULTOSC_PERIODS: [usize; 3] = {list(ULTOSC_PERIODS)!r};\n\n".replace("[", "[").replace("]", "]")
        + rust_slice("BOP_EXPECTED", bop)
        + rust_slice("CCI_EXPECTED", cci)
        + rust_slice("MFI_EXPECTED", mfi)
        + rust_slice("ULTOSC_EXPECTED", ultosc)
    )
    output_path.write_text(text)


def main() -> None:
    args = parse_args()
    with tempfile.TemporaryDirectory(prefix="fast-ta-momentum-reference-") as temporary:
        reference = TalibReference(build_pinned_talib(args.source_archive, Path(temporary)))
        try:
            emit(reference, args.output)
        finally:
            reference.close()


if __name__ == "__main__":
    main()
