// Generated by generate_momentum_change.py from the pinned mathematical
// definitions. Keep these literals independent from the production kernel.

use ta_core::Float;

pub const PERIOD: usize = 3;
pub const INPUT: &[Float] = &[
    10.0 as Float,
    11.0 as Float,
    12.0 as Float,
    15.0 as Float,
    0.0 as Float,
    20.0 as Float,
    1e-12 as Float,
    -5.0 as Float,
    25.0 as Float,
    30.0 as Float,
    5.0 as Float,
    40.0 as Float,
];

pub const MOM_EXPECTED: &[Float] = &[
    5.0 as Float,
    -11.0 as Float,
    8.0 as Float,
    -14.999999999999 as Float,
    -5.0 as Float,
    5.0 as Float,
    29.999999999999 as Float,
    10.0 as Float,
    15.0 as Float,
];

pub const ROC_EXPECTED: &[Float] = &[
    50.0 as Float,
    -100.0 as Float,
    66.66666666666667 as Float,
    -99.99999999999334 as Float,
    0.0 as Float,
    25.0 as Float,
    2_999_999_999_999_900.0 as Float,
    -200.0 as Float,
    60.00000000000001 as Float,
];

pub const ROCP_EXPECTED: &[Float] = &[
    0.5 as Float,
    -1.0 as Float,
    0.6666666666666666 as Float,
    -0.9999999999999333 as Float,
    0.0 as Float,
    0.25 as Float,
    29_999_999_999_999.004 as Float,
    -2.0 as Float,
    0.6 as Float,
];

pub const ROCR_EXPECTED: &[Float] = &[
    1.5 as Float,
    0.0 as Float,
    1.6666666666666667 as Float,
    6.666666666666667e-14 as Float,
    0.0 as Float,
    1.25 as Float,
    30_000_000_000_000.0 as Float,
    -1.0 as Float,
    1.6 as Float,
];

pub const ROCR100_EXPECTED: &[Float] = &[
    150.0 as Float,
    0.0 as Float,
    166.66666666666669 as Float,
    6.666666666666667e-12 as Float,
    0.0 as Float,
    125.0 as Float,
    3_000_000_000_000_000.0 as Float,
    -100.0 as Float,
    160.0 as Float,
];
