// Generated by tests/fixtures/generate_relative_strength.py. Do not edit by hand.
// Reference source: TA-Lib 0.8.1, commit e64d2ac896c595f38d65e44c812efbfdac8a64cf.
// Definitions: src/ta_func/ta_RSI.c, ta_CMO.c, and ta_IMI.c at that revision.

pub const PERIOD: usize = 5;
pub const TALIB_VERSION: &str = "0.8.1";
pub const TALIB_GIT_REVISION: &str = "e64d2ac896c595f38d65e44c812efbfdac8a64cf";

pub const REAL: &[f64] = &[
    44.0, 44.34, 44.09, 44.15, 43.61, 44.33, 44.83, 45.10, 45.42, 45.84, 46.08, 45.89,
];
pub const RSI_EXPECTED: &[f64] = &[
    58.638743455497382,
    68.836291913214990,
    73.282604100612978,
    77.944512301518060,
    82.853170094789141,
    85.205126704512202,
    75.021889999681966,
];
pub const CMO_EXPECTED: &[f64] = &[
    17.277486910994764,
    37.672583826429980,
    46.565208201225956,
    55.889024603036119,
    65.706340189578282,
    70.410253409024405,
    50.043779999363932,
];

pub const OPEN: &[f64] = &[10.0, 11.0, 10.0, 12.0, 12.0, 13.0, 12.0, 14.0, 13.0, 15.0];
pub const CLOSE: &[f64] = &[11.0, 10.0, 10.0, 13.0, 11.0, 14.0, 13.0, 13.0, 15.0, 15.0];
pub const IMI_EXPECTED: &[f64] = &[50.0, 50.0, 75.0, 60.0, 66.666666666666667, 80.0];
